{% set name = "colcon-ros" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 4aee34ff36927065b30b9ff85d00108e1003d0ac78a3c90b7d4357b977dda80a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - catkin_pkg >=0.4.14
    - colcon-cmake >=0.2.6
    - colcon-core >=0.7.0
    - colcon-pkg-config
    - colcon-python-setup-py >=0.2.4
    - colcon-recursive-crawl

test:
  imports:
    - colcon_ros
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    An extension for colcon-core to support ROS packages.

extra:
  recipe-maintainers:
    - j-rivero
    - seanyen
    - wolfv
