{% set name = "colcon-ros" %}
{% set version = "0.3.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 68a54a3c1190b44d2ee21881bb701ab62b1f0368bda233d900cc15b949f2991b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - catkin_pkg >=0.4.14
    - colcon-cmake >=0.2.6
    - colcon-core >=0.5.3
    - colcon-pkg-config
    - colcon-python-setup-py >=0.2.4
    - colcon-recursive-crawl

test:
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    An extension for colcon-core to support ROS packages.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
